services:
  httpfileserver:
    build: .
    image: liyaosong/qhttpfileserver:latest
    container_name: qhttpfileserver
    ports:
      - "80:80"
    volumes:
      - ./data:/data
    restart: unless-stopped
